application:
    mode: dev

log:
    # 日志名称和路径
    info_filename: logs/info.log
    error_filename: logs/error.log
    # 进行切割之前，日志文件最大值(单位：MB)，默认100MB
    max_size: 200
    # 保留旧文件的最大天数
    max_age: 30
    #  保留旧文件的最大个数
    max_backups: 7

database:
    # 支持gorm的mysql、sqlite3
    # driver: mysql
    # # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    # source: user:password@tcp(host:port)/db?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    # driver: sqlite3
    # source: sqlite3.db
    # source: host=myhost port=myport user=gorm dbname=gorm password=mypassword

redis:
    host: host
    port: port
    password: passwod
    db: 0
    pool_size: 100
    min_idle_conns: 100
